sudo: required
language: node_js
node_js:
  - "10"
  - "12"
before_install:
  - npm i -g npm
addons:
  sauce_connect: true
script: npm run test:travis

after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run clean && npm run build:dist && npx semantic-release