sudo: required
language: node_js
node_js:
  - "10"
  - "12"
before_install:
  - npm i -g npm
addons:
  sauce_connect: true
script: npm run test:travis

after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage
